language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6 gcc-6 libstdc++-6-dev
env:
  - CXX_C=g++-6 C_C=gcc-6
script: ./ci.sh
cache:
  directories:
    - deps
